version: '3.1'
services:
  softskill:
    image: mysql/mysql-server:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: softskill
    environment:
      MYSQL_ROOT_PASSWORD: flutter
      MYSQL_DATABASE: flutter
      MYSQL_USER: flutter
      MYSQL_PASSWORD: flutter
      MYSQL_TCP_PORT: 3307

    ports:
      - "3307:3307"